modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="${url_issues}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${url_homepage}"
logoFile="assets/${mod_id}/icon.png"
authors="${mod_author}"
description='''${description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"